# Ambient Runtime Node

Ambient Physical AI

## Objective

Validate the PoE-P4 as the first operational Ambient Runtime Node.

## Current Status

Phase 1 - Bringup

### Planned Components

- PoE-P4
- PaHub v2.1 (PCA9548A)
- ENV-IV
- Unit Mini OLED

### Goals

- Stable boot
- Stable serial
- PaHub detection
- ENV-IV validation
- OLED validation

## Milestone

M004 - Ambient Runtime Node Bringup


# Ambient Runtime Node — Tab5 Hardware Baseline

> **Project:** Ambient Physical AI  
> **Node:** Ambient Runtime Node  
> **Platform:** M5Stack Tab5 (ESP32-P4)  
> **Status:** Hardware Baseline Validated (Initial Version)

---

# Overview

This document records the first stable implementation of the **Ambient Runtime Node** after migrating the hardware platform from the **Unit PoE-P4** to the **M5Stack Tab5**.

The objective of this milestone was **not** to redesign the Ambient Runtime architecture, but to migrate the validated hardware infrastructure to the new platform while preserving modularity, code reuse, and engineering organization.

This document serves as the initial technical reference for the node and will evolve into the official README as development progresses.

---

# Mission

The Ambient Runtime Node is responsible for interacting with the physical environment.

Its responsibilities include:

- acquiring environmental sensor data;
- driving local displays;
- managing external I²C peripherals;
- providing runtime status visualization;
- acting as the physical execution layer of Ambient Physical AI.

The Tab5 replaces the previous PoE-P4 implementation while preserving the same architectural role.

---

# System Architecture

```text
Ambient Physical AI
│
├── Cognitive Runtime
│       AX630C + StackFlow
│
├── Ambient Runtime
│       Tab5
│
└── Expression Layer
        Distributed devices
```

The Ambient Runtime is **not** responsible for cognition.

It executes environmental sensing and physical interaction based on future semantic decisions generated by the Cognitive Runtime.

---

# Current Hardware Architecture

```text
                     Tab5 (ESP32-P4)
                           │
        ┌──────────────────┴──────────────────┐
        │                                     │
 Internal I²C                          PORT A I²C
 (Board Infrastructure)             (External Devices)
        │                                     │
        │                                     ▼
        │                                  PaHub
        │                                     │
        │               ┌───────────────┬───────────────┬───────────────┐
        │               │               │               │
        ▼               ▼               ▼               ▼
    PI4IOE1         ENV-IV         Mini OLED        DLight
    LCD Reset       CH0            CH1              CH2
    Touch Reset
```

---

# Internal I²C

The Tab5 contains its own internal I²C bus.

This bus is reserved exclusively for board infrastructure.

Current usage:

- PI4IOE1
- LCD reset
- Touch reset
- Internal control

Configuration:

```text
SDA = GPIO31
SCL = GPIO32
```

This bus **must not** be shared with external Grove devices.

---

# PORT A I²C

The PORT A connector exposes a second independent I²C bus.

Configuration:

```text
SDA = GPIO53
SCL = GPIO54
```

This bus is dedicated to:

- PaHub
- ENV-IV
- DLight
- Mini OLED
- Future Grove Units

Keeping the two buses separated greatly simplifies maintenance and future expansion.

---

# Software Organization

```text
ambient-runtime-node
│
├── components
│   │
│   ├── tab5_platform
│   │
│   ├── esp_lcd_st7121
│   │
│   ├── pahub
│   │
│   ├── env_iv
│   │
│   ├── oled_sh1107
│   │
│   └── dlight
│
└── main
```

---

# Component Responsibilities

## tab5_platform

Responsible for all Tab5-specific hardware initialization.

Current responsibilities:

- Internal I²C
- PORT A I²C
- PI4IOE1
- LCD reset
- Touch reset
- Backlight
- MIPI DSI
- ST7121 initialization
- Framebuffer
- Display control

Public APIs:

```cpp
tab5_platform_init();

tab5_platform_fill();

tab5_platform_backlight_set();

tab5_platform_get_i2c_bus();

tab5_platform_get_port_a_i2c_bus();
```

---

## esp_lcd_st7121

Dedicated display driver.

Validated features:

- ST7121 initialization
- MIPI DSI
- Framebuffer rendering

---

## pahub

Encapsulates channel selection.

Current API:

```cpp
pahub_select_channel(bus, channel);
```

Validated address:

```text
0x70
```

---

## env_iv

Environmental sensor component.

Validated devices:

### SHT40

Provides:

- Temperature
- Humidity

### BMP280

Provides:

- Temperature
- Pressure

Current APIs:

```cpp
env_iv_sht40_read();

env_iv_bmp280_read();
```

---

## oled_sh1107

Auxiliary distributed display.

Current role:

- Engineering status display
- Secondary runtime information

It is **not** the primary Ambient Runtime display.

---

## dlight

New component created for the DLight Unit.

Sensor:

```text
BH1750
```

Interface:

```text
I²C
```

Address:

```text
0x23
```

API:

```cpp
dlight_read_lux();
```

Validated reading:

```text
67.50 lx
```

---

# Current Wiring

```text
PORT A
    │
    ▼
 PaHub
    │
    ├── CH0
    │      ENV-IV
    │
    ├── CH1
    │      Mini OLED
    │
    └── CH2
           DLight
```

---

# Current Runtime Sequence

The current application performs the following initialization:

```text
Application Start

↓

Initialize Tab5 Platform

↓

Initialize Display

↓

Acquire PORT A I²C

↓

Select CH0

↓

Read ENV-IV

↓

Temperature

↓

Humidity

↓

Pressure

↓

Select CH1

↓

Update Mini OLED

↓

Select CH2

↓

Read Ambient Light

↓

Runtime Alive Loop
```

---

# Latest Validation Log

```text
Tab5 platform init OK

PaHub channel 0 selected

SHT40 Temp: 29.76 C
Humidity : 73.04 %

BMP280 Temp: 30.25 C
Pressure : 1013.24 hPa

PaHub channel 1 selected

PaHub channel 2 selected

DLight Lux: 67.50 lx

Tab5 Platform + PaHub + ENV-IV + OLED Alive
```

---

# Current Hardware Validation

## Platform

- [x] ESP32-P4
- [x] Flash 16 MB
- [x] PSRAM 32 MB
- [x] PSRAM @ 200 MHz
- [x] ST7121
- [x] MIPI DSI
- [x] LCD
- [x] Backlight
- [x] Framebuffer

---

## Internal Infrastructure

- [x] PI4IOE1
- [x] LCD Reset
- [x] Touch Reset
- [x] Internal I²C

---

## External Infrastructure

- [x] PORT A I²C
- [x] PaHub

---

## Sensors

- [x] ENV-IV
- [x] SHT40
- [x] BMP280
- [x] DLight

---

## Displays

- [x] Tab5 LCD
- [x] Mini OLED SH1107

---

# Current Status

The Tab5 hardware migration can now be considered complete.

The project is no longer focused on hardware bring-up.

The next phase is the implementation of the **Ambient Runtime Console**.

---

# Next Milestone

The next objective is transforming the current validation screen into the official engineering console.

Target layout:

```text
Ambient Physical AI
Ambient Runtime Console

--------------------------------

SYSTEM

Wi-Fi ............. Pending
Cognitive ......... Waiting
Mode .............. Standalone

--------------------------------

ENVIRONMENT

Temperature ....... xx.x °C
Humidity .......... xx %
Pressure .......... xxxx hPa
Light ............. xxxx lux

--------------------------------

I²C NETWORK

PaHub ............. OK
ENV-IV ............ OK
Mini OLED ......... OK
DLight ............ OK

--------------------------------

STATUS

READY
```

---

# Mini OLED Future Role

The Mini OLED will become a distributed auxiliary display.

Suggested layout:

```text
Ambient Runtime

READY

29.8 °C

68 lx
```

---

# Out of Scope

This milestone intentionally does **not** implement:

- MQTT
- Semantic Events
- Cognitive Runtime integration
- StackChan
- Voice Pyramid
- LVGL dashboards
- Animations
- Runtime Managers
- Architecture redesign

These belong to future milestones.

---

# Engineering Notes

One of the most important engineering decisions during this migration was keeping the board infrastructure separated from the external environment devices.

The architecture now clearly distinguishes:

```text
Tab5 Platform
        │
        ├── Internal Hardware
        │
        └── PORT A I²C
                │
                ▼
              PaHub
                │
        External Devices
```

This separation improves modularity, maintainability, and future scalability.

---

# Conclusion

The Ambient Runtime Node now provides a stable and reusable hardware foundation based on the M5Stack Tab5.

The following components have been successfully validated together:

- Tab5 Platform
- ST7121 Display
- MIPI DSI
- Internal I²C
- PORT A I²C
- PaHub
- ENV-IV
- Mini OLED SH1107
- DLight

With the hardware baseline complete, development can now focus on the Ambient Runtime Console and subsequent system integration milestones.