name=M5Echo-Pyramid
version=1.0.0
author=M5Stack
maintainer=M5Stack <support@m5stack.com>
sentence=Library for M5Stack M5Echo-Pyramid
paragraph=M5Stack M5Echo-Pyramid audio driver and control library.
category=Sensors
url=https://github.com/m5stack/M5Echo-Pyramid
architectures=esp32
includes=M5EchoPyramid.h