#!/usr/bin/env python3
"""
Echo Pyramid communication adapter for Ambient Physical AI.

This module translates normalized Semantic Event V1 objects into the compact
UDP command contract supported by the Echo Pyramid Voice Node.

Protocol contract
-----------------
The adapter preserves the legacy compact commands already validated by the
system:

    WELCOME
    RED
    GREEN
    BLUE
    OFF

For authenticated-user welcome events, the protocol may append a safe profile
identifier or display name:

    WELCOME|claudio

The Voice Node must remain backward compatible with both ``WELCOME`` and
``WELCOME|<name>``. Semantic decisions remain centralized in the AX630C;
the Echo Pyramid only executes the command it receives.
"""

import os
import socket
from typing import Any, Dict, Mapping, Optional

from semantic_event import is_semantic_event


class EchoPyramidAdapter:
    """
    Deliver supported Semantic Events to the Echo Pyramid Voice Node.

    The adapter owns only protocol translation and UDP delivery. It does not
    decide user authorization, context, or cognitive behavior.
    """

    DEFAULT_HOST = "192.168.77.31"
    DEFAULT_PORT = 5005

    EVENT_COMMAND_MAP: Dict[str, str] = {
        # Canonical event generated by the current Cognitive Runtime.
        "identity_authenticated": "WELCOME",
        # Legacy welcome events remain supported during system transition.
        "welcome_researcher": "WELCOME",
        "welcome_student": "WELCOME",
        "welcome_visitor": "WELCOME",
        # Existing RGB commands must remain unchanged.
        "rgb_red": "RED",
        "rgb_green": "GREEN",
        "rgb_blue": "BLUE",
        "rgb_off": "OFF",
    }

    def __init__(self) -> None:
        """
        Initialize delivery configuration from environment variables.

        Environment variables keep deployment-specific network settings out of
        the source code while preserving the validated laboratory defaults.
        """

        self.mode = os.getenv(
            "ECHO_PYRAMID_NOTIFY_MODE",
            "udp",
        ).strip().lower()

        self.host = os.getenv(
            "ECHO_PYRAMID_HOST",
            self.DEFAULT_HOST,
        ).strip()

        port_value = os.getenv(
            "ECHO_PYRAMID_PORT",
            str(self.DEFAULT_PORT),
        ).strip()

        try:
            self.port = int(port_value)
        except ValueError:
            print(
                "Echo Pyramid configuration warning: "
                f"invalid port [{port_value}]; using {self.DEFAULT_PORT}."
            )
            self.port = self.DEFAULT_PORT

    def notify(self, semantic_event: Mapping[str, Any]) -> bool:
        """
        Translate and deliver one normalized Semantic Event V1.

        Unsupported events are intentionally ignored because this expression
        adapter is not expected to react to every Runtime event. Returning
        ``True`` for an unsupported event prevents an irrelevant event from
        being treated as a transport failure by the dispatcher.
        """

        if not is_semantic_event(semantic_event):
            raise ValueError("invalid Semantic Event V1")

        event_name = self._extract_event_name(semantic_event)

        if event_name is None:
            raise ValueError(
                "Semantic Event does not contain a valid event name"
            )

        print(f"[Echo Pyramid] Semantic event received: {event_name}")

        command = self._build_command(
            event_name=event_name,
            semantic_event=semantic_event,
        )

        if command is None:
            print(
                "Echo Pyramid event ignored: "
                f"unsupported semantic event [{event_name}]"
            )
            return True

        if self.mode != "udp":
            print(f"Echo Pyramid command prepared: {command}")
            print("Echo Pyramid delivery: DISABLED")
            return False

        return self._notify_udp(command)

    @staticmethod
    def _extract_event_name(
        semantic_event: Mapping[str, Any],
    ) -> Optional[str]:
        """
        Extract the actionable semantic event name.

        Some Runtime versions store the canonical action in ``event_type``;
        older producers may store it in ``event`` while using
        ``event_type=semantic_event`` as a generic envelope marker. Both forms
        are accepted to preserve compatibility.
        """

        event_type = semantic_event.get("event_type")

        if isinstance(event_type, str) and event_type.strip():
            normalized = event_type.strip().lower()

            if normalized != "semantic_event":
                return normalized

        legacy_event = semantic_event.get("event")

        if isinstance(legacy_event, str) and legacy_event.strip():
            return legacy_event.strip().lower()

        return None

    def _build_command(
        self,
        event_name: str,
        semantic_event: Mapping[str, Any],
    ) -> Optional[str]:
        """
        Build the compact command sent to the Echo Pyramid.

        Only welcome commands are enriched with an optional user name. All
        other validated commands remain byte-for-byte compatible with the
        previous protocol.

        Examples:
            ``WELCOME``
            ``WELCOME|claudio``
            ``RED``
        """

        base_command = self.EVENT_COMMAND_MAP.get(event_name)

        if base_command is None:
            return None

        if base_command != "WELCOME":
            return base_command

        profile_name = self._extract_profile_name(semantic_event)

        if profile_name is None:
            # Preserve the already validated legacy behavior when no usable
            # profile name is present in the semantic event.
            return base_command

        return f"{base_command}|{profile_name}"

    @classmethod
    def _extract_profile_name(
        cls,
        semantic_event: Mapping[str, Any],
    ) -> Optional[str]:
        """
        Resolve a safe user-facing identifier from known event structures.

        The Runtime has evolved through more than one event shape. The search
        therefore checks the top-level profile and common nested payload
        containers without changing the Semantic Event contract.

        Preferred fields:
            ``display_name`` -> ``name`` -> ``id`` -> ``role``

        The returned value is sanitized for the compact ``COMMAND|parameter``
        protocol so delimiters and control characters cannot corrupt the UDP
        message.
        """

        candidate_containers = [
            semantic_event.get("profile"),
            semantic_event.get("user"),
            semantic_event.get("identity"),
        ]

        for envelope_key in ("payload", "data", "context"):
            envelope = semantic_event.get(envelope_key)

            if isinstance(envelope, Mapping):
                candidate_containers.extend(
                    [
                        envelope.get("profile"),
                        envelope.get("user"),
                        envelope.get("identity"),
                    ]
                )

        # Current Semantic Event Generator (V1) exposes authenticated user
        # information directly inside the payload/context objects instead of
        # nested profile/user/identity dictionaries.
        payload = semantic_event.get("payload")
        if isinstance(payload, Mapping):
            for field_name in ("user_name", "user_id"):
                sanitized = cls._sanitize_parameter(payload.get(field_name))
                if sanitized is not None:
                    return sanitized

        context = semantic_event.get("context")
        if isinstance(context, Mapping):
            for field_name in ("active_user", "user_name", "user_id"):
                sanitized = cls._sanitize_parameter(context.get(field_name))
                if sanitized is not None:
                    return sanitized

        for container in candidate_containers:
            if not isinstance(container, Mapping):
                continue

            for field_name in ("display_name", "name", "id", "role"):
                value = container.get(field_name)
                sanitized = cls._sanitize_parameter(value)

                if sanitized is not None:
                    return sanitized

        # Some producers may expose a direct profile/user field as a string.
        for direct_field in (
            "display_name",
            "user_name",
            "profile_name",
            "profile_id",
        ):
            sanitized = cls._sanitize_parameter(
                semantic_event.get(direct_field)
            )

            if sanitized is not None:
                return sanitized

        return None

    @staticmethod
    def _sanitize_parameter(value: Any) -> Optional[str]:
        """
        Sanitize one compact-protocol parameter.

        The pipe character is the field delimiter. Newlines and other control
        characters are removed because the embedded receiver expects one
        single-line UDP command.
        """

        if not isinstance(value, str):
            return None

        normalized = " ".join(value.strip().split())

        if not normalized:
            return None

        normalized = normalized.replace("|", " ")

        # Keep packets compact for the embedded receiver and avoid accidental
        # oversized messages caused by malformed upstream data.
        normalized = normalized[:64].strip()

        return normalized or None

    def _notify_udp(self, command: str) -> bool:
        """
        Send one compact command to the Echo Pyramid through UDP.

        UDP is intentionally used because the Cognitive Runtime has already
        made the semantic decision. The embedded Voice Node receives only a
        lightweight execution command, preserving centralized cognition in the
        AX630C and keeping the firmware contract simple.
        """

        if not self.host:
            print(
                "Echo Pyramid UDP mode selected, "
                "but no host is configured."
            )
            return False

        if self.port <= 0 or self.port > 65535:
            print(
                "Echo Pyramid UDP mode selected, "
                "but the port is invalid."
            )
            return False

        try:
            with socket.socket(
                socket.AF_INET,
                socket.SOCK_DGRAM,
            ) as sock:
                sock.sendto(
                    command.encode("utf-8"),
                    (self.host, self.port),
                )

            print(
                "Echo Pyramid command sent: "
                f"{command} -> {self.host}:{self.port}"
            )
            return True

        except OSError as exc:
            print(
                "Echo Pyramid delivery failed for "
                f"{self.host}:{self.port}: {exc}"
            )
            return False
