#!/usr/bin/env python3
"""
RGB Expression Nodes notifier for Ambient Physical AI.

Consumes normalized Semantic Event V1 objects and delivers the same compact
Expression Layer message to every configured RGB expression node through UDP.

This adapter does not generate semantic meaning and does not alter the
normalized runtime event. Its responsibility is limited to translating the
event into the delivery contract supported by the RGB expression nodes and
sending that message to each configured destination.
"""

import json
import os
import socket
from typing import List, Tuple

from semantic_event import is_semantic_event


class RGBStripNotifier:
    """
    Deliver Semantic Event V1 messages to the RGB expression nodes.

    The historical class name is preserved to avoid changing the adapter
    registration contract used by the Cognitive Runtime. Internally, the
    notifier now supports all production RGB nodes that implement the same
    UDP semantic-event protocol.

    Default production destinations:

    RGB Strip Node       192.168.77.26:5555
    Atom Matrix Node     192.168.77.28:5555

    The StickC Plus 2 is intentionally excluded because it consumes the
    dedicated Runtime State protocol rather than Semantic Events.
    """

    DEFAULT_HOSTS = (
        "192.168.77.26",
        "192.168.77.28",
    )

    def __init__(self):
        """
        Initialize the RGB expression delivery adapter.

        Environment variables preserve deployment flexibility without
        changing the production defaults:

        RGB_STRIP_NOTIFY_MODE
            Delivery mode. The supported active mode is ``udp``.

        RGB_EXPRESSION_HOSTS
            Optional comma-separated list of RGB node IPv4 addresses.

        RGB_STRIP_HOST
            Legacy single-host configuration. It remains supported for
            compatibility and is used only when RGB_EXPRESSION_HOSTS is not
            defined.

        RGB_STRIP_PORT
            UDP destination port shared by all RGB expression nodes.
        """
        self.mode = os.getenv(
            "RGB_STRIP_NOTIFY_MODE",
            "udp",
        ).strip().lower()

        self.port = int(
            os.getenv(
                "RGB_STRIP_PORT",
                "5555",
            )
        )

        self.hosts = self._load_hosts()

    def _load_hosts(self) -> List[str]:
        """
        Resolve and validate the configured RGB node destinations.

        The multi-node environment variable has priority. The legacy
        RGB_STRIP_HOST variable is retained so existing single-node
        deployments are not broken.

        Returns:
            Ordered list of unique, non-empty destination addresses.
        """
        configured_hosts = os.getenv("RGB_EXPRESSION_HOSTS")

        if configured_hosts:
            raw_hosts = configured_hosts.split(",")
        else:
            legacy_host = os.getenv("RGB_STRIP_HOST")

            if legacy_host:
                raw_hosts = [legacy_host]
            else:
                raw_hosts = list(self.DEFAULT_HOSTS)

        hosts = []
        seen = set()

        for raw_host in raw_hosts:
            host = raw_host.strip()

            if not host or host in seen:
                continue

            hosts.append(host)
            seen.add(host)

        return hosts

    def notify(self, semantic_event) -> bool:
        """
        Consume and deliver one normalized Semantic Event V1.

        Every configured RGB node receives the same compact payload. Delivery
        succeeds only when the event is sent successfully to every configured
        destination.

        Args:
            semantic_event:
                Normalized Semantic Event V1 generated by the Cognitive
                Runtime.

        Returns:
            True when every configured UDP delivery succeeds.
            False when delivery is disabled, no destination is configured,
            or at least one destination fails.
        """
        if not is_semantic_event(semantic_event):
            raise ValueError("invalid Semantic Event V1")

        event_name = (
            semantic_event.get("event_type")
            or semantic_event.get("event")
        )

        if not isinstance(event_name, str) or not event_name.strip():
            raise ValueError(
                "Semantic Event does not contain a valid event"
            )

        event_payload = semantic_event.get("payload", {})

        if not isinstance(event_payload, dict):
            event_payload = {}

        payload = {
            "type": "semantic_event",
            "event": event_name.strip(),
            "target": "rgb_strip",
            "payload": {
                "user_id": str(
                    event_payload.get("user_id", "unknown")
                ).strip().lower(),
            },
        }

        if self.mode == "udp":
            return self._notify_udp(payload)

        print("\nRGB expression semantic message prepared:")
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        print("RGB expression delivery: DISABLED")

        return False

    def _notify_udp(self, payload) -> bool:
        """
        Send one semantic payload to all configured RGB expression nodes.

        UDP does not provide application-level delivery confirmation. A
        successful result means that the operating system accepted every
        datagram for transmission. Physical-node reaction must still be
        confirmed through integration testing.

        Args:
            payload:
                Compact semantic-event message understood by the RGB nodes.

        Returns:
            True when sendto succeeds for all configured destinations.
            False when configuration is invalid or any send operation fails.
        """
        if not self.hosts:
            print(
                "RGB expression UDP mode selected, "
                "but no hosts are configured."
            )
            return False

        if self.port <= 0 or self.port > 65535:
            print(
                "RGB expression UDP mode selected, "
                "but the port is invalid."
            )
            return False

        data = json.dumps(
            payload,
            ensure_ascii=False,
        ).encode("utf-8")

        delivery_results: List[Tuple[str, bool]] = []

        for host in self.hosts:
            delivered = self._send_datagram(
                host,
                data,
            )

            delivery_results.append(
                (host, delivered)
            )

        successful_deliveries = sum(
            1
            for _, delivered in delivery_results
            if delivered
        )

        print(
            "RGB expression delivery summary: "
            f"{successful_deliveries}/{len(delivery_results)} sent"
        )

        return all(
            delivered
            for _, delivered in delivery_results
        )

    def _send_datagram(
        self,
        host: str,
        data: bytes,
    ) -> bool:
        """
        Send one already serialized datagram to one RGB node.

        Isolating each destination prevents a failure in one node from
        blocking delivery attempts to the remaining expression nodes.

        Args:
            host:
                Destination IPv4 address or hostname.

            data:
                UTF-8 JSON datagram ready for transmission.

        Returns:
            True when the datagram is accepted for transmission.
            False when socket creation or transmission fails.
        """
        try:
            with socket.socket(
                socket.AF_INET,
                socket.SOCK_DGRAM,
            ) as sock:
                sock.sendto(
                    data,
                    (host, self.port),
                )

            print(
                "RGB expression semantic event sent to "
                f"{host}:{self.port}"
            )

            return True

        except OSError as exc:
            print(
                "RGB expression semantic event delivery failed for "
                f"{host}:{self.port}: {exc}"
            )

            return False