idf_component_register(
    SRCS
        "main.c"
        "audio_bridge.cpp"
        "network_config.c"
        "display_manager.c"
        "lcd_driver.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_driver_i2c
    PRIV_REQUIRES
        esp_event
        esp_netif
        esp_wifi
        nvs_flash
        lwip
        esp_system
        M5Echo-Pyramid
        voice_receiver
        wake_word_detector
)